name: Keep Render Backend Alive

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Backend
        run: curl -X GET https://your-backend-url.onrender.com/actuator/health
